require 'net/http'
require 'uri'
require 'json'

class AiChatController < ApplicationController
  before_action :authorize

  def prompt
    user_message = params[:message]

    # DeepSeek API endpoint y tu API key
    uri = URI.parse('https://api.deepseek.com/v1/chat/completions')
    api_key = ENV['DEEPSEEK_API_KEY']

    messages = [{ "role": 'system', "content": system_prompt },
                { "role": 'user', "content": user_message }]

    payload = {
      model: 'deepseek-chat',
      messages: messages,
      response_format: { type: 'json_object' } # <--- Esto fuerza salida JSON si la API lo soporta
    }

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.open_timeout = 60    # 1 minuto
    http.read_timeout = 60    # 1 minuto
    request = Net::HTTP::Post.new(uri.request_uri)
    request['Authorization'] = "Bearer #{api_key}"
    request['Content-Type'] = 'application/json'
    request.body = payload.to_json

    response = http.request(request)
    result = JSON.parse(response.body)
    byebug
    # Ajusta según la estructura real de la respuesta de DeepSeek
    ai_response = result.dig('choices', 0, 'message', 'content') || 'No response from DeepSeek'
    render json: { response: ai_response }
  end

  private

  def system_prompt
    <<~PROMPT
            The user will provide some restaurant menu. Please parse the "question" and "explication" and "code" and output them in JSON format.#{' '}

        EXAMPLE INPUT:#{' '}
        menu de sushi minimalista con dos columnas#{' '}

        EXAMPLE JSON OUTPUT:
        {
            "question": " menu de sushi minimalista con dos columnas",
            "explication": "some explication about the menu",
            "code": the react code to render the menu using Chakra UI components, only the return()  without the <chackProvider> and without the return, only the code#{' '}
        }
      """
            hace un menu digital para un restuarant usando estos componentes de chackra ui
      "ChakraBaseProvider"
      "ChakraProvider"
      "Accordion"
      "AccordionButton"
      "useAccordionStyles"
      "AccordionIcon"
      "AccordionItem"
      "AccordionPanel"
      "AccordionProvider"
      "useAccordion"
      "useAccordionContext"
      "useAccordionItem"
      "useAccordionItemState"
      "Alert"
      "useAlertContext"
      "useAlertStyles"
      "AlertDescription"
      "AlertIcon"
      "AlertTitle"
      "AspectRatio"
      "Avatar"
      "AvatarBadge"
      "useAvatarStyles"
      "AvatarGroup"
      "GenericAvatarIcon"
      "Badge"
      "Box"
      "Square"
      "Circle"
      "Breadcrumb"
      "useBreadcrumbStyles"
      "BreadcrumbItem"
      "BreadcrumbLink"
      "BreadcrumbSeparator"
      "Button"
      "ButtonGroup"
      "IconButton"
      "ButtonSpinner"
      "useButtonGroup"
      "Card"
      "CardBody"
      "useCardStyles"
      "CardFooter"
      "CardHeader"
      "AbsoluteCenter"
      "Center"
      "Checkbox"
      "CheckboxGroup"
      "CheckboxIcon"
      "useCheckbox"
      "useCheckboxGroup"
      "CloseButton"
      "Code"
      "ColorModeProvider"
      "DarkMode"
      "LightMode"
      "cookieStorageManager"
      "cookieStorageManagerSSR"
      "createCookieStorageManager"
      "createLocalStorageManager"
      "localStorageManager"
      "ColorModeScript"
      "getScriptSrc"
      "ColorModeContext"
      "useColorMode"
      "useColorModeValue"
      "Container"
      "ControlBox"
      "CSSPolyfill"
      "CSSReset"
      "Divider"
      "Editable"
      "useEditableContext"
      "useEditableStyles"
      "EditableInput"
      "EditablePreview"
      "EditableTextarea"
      "useEditable"
      "useEditableControls"
      "useEditableState"
      "EnvironmentProvider"
      "useEnvironment"
      "createExtendTheme"
      "extendBaseTheme"
      "extendTheme"
      "mergeThemeOverride"
      "withDefaultColorScheme"
      "withDefaultProps"
      "withDefaultSize"
      "withDefaultVariant"
      "Flex"
      "FocusLock"
      "FormControl"
      "FormHelperText"
      "useFormControlContext"
      "useFormControlStyles"
      "useFormControl"
      "useFormControlProps"
      "FormErrorIcon"
      "FormErrorMessage"
      "useFormErrorStyles"
      "FormLabel"
      "RequiredIndicator"
      "Grid"
      "GridItem"
      "SimpleGrid"
      "Highlight"
      "Mark"
      "useHighlight"
      "createIcon"
      "Icon"
      "Image"
      "Img"
      "useImage"
      "Indicator"
      "Input"
      "InputAddon"
      "InputLeftAddon"
      "InputRightAddon"
      "InputGroup"
      "useInputGroupStyles"
      "InputLeftElement"
      "InputRightElement"
      "Kbd"
      "Link"
      "LinkBox"
      "LinkOverlay"
      "List"
      "ListIcon"
      "ListItem"
      "OrderedList"
      "UnorderedList"
      "useListStyles"
      "Hide"
      "useQuery"
      "useColorModePreference"
      "usePrefersReducedMotion"
      "Show"
      "useBreakpoint"
      "useBreakpointValue"
      "useMediaQuery"
      "Menu"
      "useMenuStyles"
      "MenuButton"
      "MenuCommand"
      "MenuDivider"
      "MenuGroup"
      "MenuIcon"
      "MenuItem"
      "MenuItemOption"
      "MenuList"
      "MenuOptionGroup"
      "MenuDescendantsProvider"
      "MenuProvider"
      "useMenu"
      "useMenuButton"
      "useMenuContext"
      "useMenuDescendant"
      "useMenuDescendants"
      "useMenuDescendantsContext"
      "useMenuItem"
      "useMenuList"
      "useMenuOption"
      "useMenuOptionGroup"
      "useMenuPositioner"
      "useMenuState"
      "AlertDialog"
      "AlertDialogContent"
      "AlertDialogBody"
      "DrawerBody"
      "ModalBody"
      "AlertDialogCloseButton"
      "DrawerCloseButton"
      "ModalCloseButton"
      "AlertDialogFooter"
      "DrawerFooter"
      "ModalFooter"
      "AlertDialogHeader"
      "DrawerHeader"
      "ModalHeader"
      "AlertDialogOverlay"
      "DrawerOverlay"
      "ModalOverlay"
      "Drawer"
      "useDrawerContext"
      "DrawerContent"
      "Modal"
      "ModalContextProvider"
      "useModalContext"
      "useModalStyles"
      "ModalContent"
      "ModalFocusScope"
      "useModal"
      "useModalManager"
      "NumberDecrementStepper"
      "NumberIncrementStepper"
      "NumberInput"
      "NumberInputField"
      "NumberInputStepper"
      "useNumberInputStyles"
      "useNumberInput"
      "PinInput"
      "PinInputField"
      "PinInputDescendantsProvider"
      "PinInputProvider"
      "usePinInput"
      "usePinInputContext"
      "usePinInputField"
      "Popover"
      "usePopover"
      "PopoverAnchor"
      "PopoverArrow"
      "PopoverBody"
      "PopoverCloseButton"
      "PopoverContent"
      "PopoverFooter"
      "PopoverHeader"
      "PopoverTrigger"
      "usePopoverContext"
      "usePopoverStyles"
      "usePopper"
      "popperCSSVars"
      "PortalManager"
      "usePortalManager"
      "Portal"
      "CircularProgress"
      "Progress"
      "useProgressStyles"
      "ProgressLabel"
      "CircularProgressLabel"
      "Radio"
      "useRadio"
      "useRadioGroup"
      "RadioGroup"
      "useRadioGroupContext"
      "Select"
      "SelectField"
      "Skeleton"
      "SkeletonText"
      "SkeletonCircle"
      "SkipNavContent"
      "SkipNavLink"
      "RangeSlider"
      "RangeSliderFilledTrack"
      "RangeSliderMark"
      "RangeSliderProvider"
      "RangeSliderThumb"
      "RangeSliderTrack"
      "useRangeSliderContext"
      "useRangeSliderStyles"
      "Slider"
      "SliderFilledTrack"
      "SliderMark"
      "SliderProvider"
      "SliderThumb"
      "SliderTrack"
      "useSliderContext"
      "useSliderStyles"
      "useRangeSlider"
      "useSlider"
      "Spacer"
      "Spinner"
      "HStack"
      "Stack"
      "StackDivider"
      "VStack"
      "Stat"
      "useStatStyles"
      "StatArrow"
      "StatDownArrow"
      "StatUpArrow"
      "StatGroup"
      "StatHelpText"
      "StatLabel"
      "StatNumber"
      "Step"
      "useStepContext"
      "useStepperStyles"
      "StepDescription"
      "StepIcon"
      "StepIndicator"
      "StepIndicatorContent"
      "StepNumber"
      "StepSeparator"
      "StepStatus"
      "StepTitle"
      "Stepper"
      "useSteps"
      "Switch"
      "shouldForwardProp"
      "useTheme"
      "getToken"
      "useChakra"
      "useToken"
      "CSSVars"
      "GlobalStyle"
      "StylesProvider"
      "ThemeProvider"
      "createStylesContext"
      "useStyles"
      "styled"
      "toCSSObject"
      "forwardRef"
      "useMultiStyleConfig"
      "useStyleConfig"
      "chakra"
      "Table"
      "useTableStyles"
      "TableCaption"
      "TableContainer"
      "Tbody"
      "Td"
      "Tfoot"
      "Th"
      "Thead"
      "Tr"
      "Tab"
      "TabIndicator"
      "TabList"
      "TabPanel"
      "TabPanels"
      "Tabs"
      "useTabsStyles"
      "TabsDescendantsProvider"
      "TabsProvider"
      "useTab"
      "useTabIndicator"
      "useTabList"
      "useTabPanel"
      "useTabPanels"
      "useTabs"
      "useTabsContext"
      "useTabsDescendant"
      "useTabsDescendants"
      "useTabsDescendantsContext"
      "Tag"
      "TagCloseButton"
      "TagLabel"
      "TagLeftIcon"
      "TagRightIcon"
      "useTagStyles"
      "Textarea"
      "createStandaloneToast"
      "createToastFn"
      "Toast"
      "createRenderToast"
      "getToastPlacement"
      "ToastOptionProvider"
      "ToastProvider"
      "toastStore"
      "useToast"
      "Tooltip"
      "useTooltip"
      "Collapse"
      "Fade"
      "fadeConfig"
      "ScaleFade"
      "scaleFadeConfig"
      "Slide"
      "SlideFade"
      "slideFadeConfig"
      "EASINGS"
      "getSlideTransition"
      "withDelay"
      "Heading"
      "Text"
      "VisuallyHidden"
      "VisuallyHiddenInput"
      "visuallyHiddenStyle"
      "Wrap"
      "WrapItem"
      "useAnimationState"
      "useBoolean"
      "useCallbackRef"
      "useClipboard"
      "useConst"
      "useControllableProp"
      "useControllableState"
      "useCounter"
      "useDisclosure"
      "useEventListener"
      "useFocusOnHide"
      "useFocusOnShow"
      "useFocusOnPointerDown"
      "useId"
      "useIds"
      "useOptionalPart"
      "useInterval"
      "useLatestRef"
      "mergeRefs"
      "useMergeRefs"
      "useOutsideClick"
      "usePrevious"
      "useSafeLayoutEffect"
      "useSize"
      "useSizes"
      "useTimeout"
      "useUpdateEffect"
      "usePanEvent"
      "css"
      "getCss"
      "createMultiStyleConfigHelpers"
      "defineStyle"
      "defineStyleConfig"
      "getCSSVar"
      "pseudoPropNames"
      "pseudoSelectors"
      "resolveStyleConfig"
      "isStyleProp"
      "layoutPropNames"
      "propNames"
      "systemProps"
      "omitThemingProps"
      "tokenToCSSVar"
      "background"
      "border"
      "color"
      "effect"
      "filter"
      "flexbox"
      "grid"
      "interactivity"
      "layout"
      "list"
      "others"
      "position"
      "ring"
      "space"
      "textDecoration"
      "transform"
      "transition"
      "typography"
      "scroll"
      "calc"
      "addPrefix"
      "cssVar"
      "defineCssVars"
      "toVarDefinition"
      "toVarReference"
      "toCSSVar"
      "flattenTokens"
      "isChakraTheme"
      "requiredChakraThemeKeys"
      "baseTheme"
      "theme"


    PROMPT
  end
end
